name: todo_repository
description: Dart package which manages the todos domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  todos_database_hive:
    path: ../todos_database_hive

  equatable: ^2.0.3
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0